name: javadev865-streamlit-fastai-env
dependencies:
        - python=3.7
        - numpy
        - pandas
        - pip:
                - torch
                - torchvision
                - fastai
                - streamlit
